### ISSUE TITLE
Is conda.recipe/meta.yml wrong?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/OG-USA#393]
Here is what the top of the file looks like:
```
package:
  name: ogusa
  version: 0.5.10

requirements:
  build:
    - python
    - pip
    - matplotlib
    - numpy >=1.12.1
    - pandas >=0.20.1
    - scipy
    - setuptools
    - taxcalc
```
My question is how can the taxcalc package be found when doing a conda build when it's on the ospc channel and there is no specification of the ospc channel?

@hdoupe,  You explained the need for non-default channels to be specified recently in the taxdata repo.  Doesn't your recent explanation apply here?

@jdebacker @rickecon
